### ISSUE TITLE
[model] Kiểm tra tài khoản đã được đăng ký chưa?

### ISSUE THREAD

**Issue by meosgroup** [meosgroup/iforum#2]
Thiết kế một hàm kiểm tra boolean isRegisted(String username, String password) để kiểm tra một tài khoản đã đăng ký chưua

**Comment by 0xdu** [comment]
sử dụng chức năng  thêm bạn bè của web để kiểm tra một tài khoản có tồn tại hay không.
Cho phép sử dụng request để kiểm tra

**Comment by meosgroup** [comment]
Cái này hỗ trợ lúc đăng ký hàng loạt, kiểm tra trước thì skip qua các tài khoản k hợp lệ luôn

**Comment by 0xdu** [comment]
Done
