### ISSUE TITLE
[model] Bắt sự kiện đăng ký, đăgn nhập và đăng bài thành công

### ISSUE THREAD

**Issue by meosgroup** [meosgroup/iforum#5]
Hiện tại các bước đăng nhập, đăng bài đang thực hiện tuần tự và mặc định không có kiểm tra xem bước thực hiện đó đã thành công hay chưa. Điều này sẽ làm ảnh hưởng tới bên Views khi không thể update trạng thái của công việc.
Do đó cần có một tín hiệu trả về cho các thao tác 

`login`,  `post`, `register` là đã thành công hay chưa.

**Comment by 0xdu** [comment]
login, post bài theo request done, register theo selenium done
